spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/barber_shop
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  # flyway:
  #   repair-on-migrate: true
